from i_product_selection import IProductSelection


class ReactionChemistry(IProductSelection):

    def __init__(self, chemistry, product_selection):
        self.chemistry = chemistry
        self.product_selection = product_selection

    def get_products(self, reactants):

        """
        Return one set of products from the set of all possible sets of products of the
        reaction generated by the chemistry. The particular product set returned is chosen by the
        function provided as the ReactionChemistry's selection parameter.

        :param reactants: [IElements]
        :return: [IElements]
        """

        if not isinstance(reactants, list):
            raise TypeError

        if len(reactants) < 1:
            raise ValueError

        intermediate = self.chemistry.join(reactants)
        products = self.chemistry.split(intermediate)

        return self.product_selection(products)
